name = "Sodium Plus"
author = "NoSadBeHappy, RedstoneWizard08"
version = "2.0.0-beta2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "421d1befdf324f3e4ae681e91218aea3e5d0d89a12e60cd0d7f5b5ff022638de"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
