name = "Sodium Plus"
author = "NoSadBeHappy, RedstoneWizard08"
version = "2.0.0-beta4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d2df962cba3cb26da832e456f9f71005e9652acdd4261a7baa1088f85c47b4b"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
