name = "Sodium Plus"
author = "NoSadBeHappy, RedstoneWizard08"
version = "2.0.0-beta1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eadd5873b4c02223dac1713c2afe5e3d6f7e6d081f0e030d8446dabb0d222ee"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
