name = "Sodium Plus"
author = "HappyRedstone Modding"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b37c6df373bf9c9ecbc84e7a490d7518992c1a777bc52df0e582f6574481f30"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1"]
