name = "Sodium Plus"
author = "NoSadBeHappy"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be0917fa7b7d885fd4bdb23b42857b7a7d5cfdbf228d7b47c050d11baeeebecb"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
