name = "Sodium Plus"
author = "NoSadBeHappy, RedstoneWizard08"
version = "2.0.0-beta1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80cce1920ab226016474a3ea4b45f9515bd0c15d5c4a6a4eed8acc8835a15b68"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
