name = "Sodium Plus"
author = "NoSadBeHappy"
<<<<<<< HEAD
version = "2.2.10"
=======
version = "2.2.9"
>>>>>>> parent of 94793cc (Merge branch 'main' of https://github.com/NoSadBeHappy/sodiumplus)
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
<<<<<<< HEAD
hash = "c448909a966bebfc4b453da62a4ade78d15f84cdca4b4e519e45bc9360a30abe"
=======
hash = "db5f9aa33cc224a675dde1daf08d92cdaf34e3c2990f8d8113f3db35dd41d328"
>>>>>>> parent of 94793cc (Merge branch 'main' of https://github.com/NoSadBeHappy/sodiumplus)

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"

[options]
<<<<<<< HEAD
acceptable-game-versions = ["1.20.1", "1.20", "1.19"]
=======
acceptable-game-versions = ["1.20.1", "1.20", "1.19", "1.16.5"]
>>>>>>> parent of 94793cc (Merge branch 'main' of https://github.com/NoSadBeHappy/sodiumplus)
