name = "Sodium Plus"
author = "HappyRedstone Modding"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e08328df45bafb3a36f55798889bfa2104aed6b5f487fa578382e95b12f7ad7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1"]
