name = "Sodium Plus"
author = "NoSadBeHappy"
version = "2.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88f27ad870115632f15ff24be2e40274c51fa57fe96a01d53f54c140a956d4e5"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
acceptable-game-versions = ["1.20.1", "1.20", "1.19", "1.16.5"]
