name: Build binaries
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
      env:
        GOPATH: /__w/sodiumplus/go/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: go/src/github.com/HappyRedstone/SodiumPlus

    - name: Build
      run: make -C go/src/github.com/HappyRedstone/SodiumPlus

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: bin/*
