name: Build binaries
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: make
      env:
        GOPATH: /home/runner/work/sodiumplus/go
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: bin
